### Go to root
GET http://localhost:3000/


### Get messages
GET http://localhost:3000/messages

### Create a message
POST http://localhost:3000/messages
Content-Type: application/json

{
  "sender": "Manas",
  "content": "DI added"
}

### Get a message
GET http://localhost:3000/messages/589
